class: Anova
params:
  method: "anova_bootstrapped_es"
  group_contrast: 'C(Group, Sum)'
  covariates: ['Alter', 'Geschlecht', 'Dummy_BC_MR_pre', 'Dummy_BC_MR_post']
  ss_type: 3
  n_bootstrap: 1000
  skip: False