setup:
  analysis_name: "DTI Network Parameter"
  result_dir: "../results/dti/"
  filter_name:
    partial: 'configs/partials/sample_filter_site.yaml'
preprocessing:
  class: GraphMetricsDTI
  params:
    subjects: '../raw_data/dti/DTI_DataFreeze1-3-30092020_macbook.csv'
    dti_parameter_file: '/spm-data/Scratch/spielwiese_julian_blanke/modality_pipeline_data/dti/number_of_streamlines.pkl'
    dti_nos_file: '/spm-data/Scratch/spielwiese_julian_blanke/modality_pipeline_data/dti/number_of_streamlines.pkl'
    output_path: '../data/dti/graph_metrics/'
    metrics:
      - 'global_efficiency'
      - 'local_efficiency'
      - 'clustering'
      - 'average_clustering'
      - 'degree_centrality'
      - 'average_degree_centrality'
      - 'betweenness_centrality'
      - 'average_betweenness_centrality'
      - 'degree_assortativity_coefficient'
    n_processes: 10
    skip: True
data:
  class: GraphMetricsDTIData
  params:
    pheno_file: '../raw_data/dti/DTI_DataFreeze1-3-30092020_macbook.csv'
    data_path: '../data/dti/graph_metrics/'
    skip: False
statistics:
  partial: 'configs/partials/statistics_mri_site.yaml'
plot:
  partial: 'configs/partials/pipeline_plot.yaml'

