setup:
  analysis_name: "SocialSupport_no_BDI"
  result_dir: "../results/clinical/"
  filter_name:
    partial: 'configs/partials/sample_filter_gender.yaml'
data:
  class: ClinicalData
  params:
    sample_file: '../raw_data/clinical/Clinical_DataFreeze1-3-30102020_macbook.csv'
    variables:
      - "FSozU_Sum"
    skip:  False
statistics:
  class: Anova
  params:
    method: "mass_anova"
    group_contrast: 'C(Group, Sum)'
    covariates: [ 'Alter', 'Site', 'BDI_Sum' ]
    ss_type: 3
    n_bootstrap: 1000
    skip: True
plot:
  partial: 'configs/partials/pipeline_plot.yaml'
