setup:
  analysis_name: "Contrast 0002"
  result_dir: "../results/all/"
  filter_name:
    - "filter_all"
plot:
  class: SummaryPlotMatplotlib
  params:
    corrected_p: True
    plot_p_values: False
    use_sample_filter: False
    result_folder_analyses:
      - '../results/protect_ad/Contrast 0002/all'
      - '../results/protect_ad/Contrast 0003/all'
      - '../results/protect_ad/Contrast 0004/all'
      - '../results/protect_ad/Contrast 0005/all'
      - '../results/protect_ad/Contrast 0006/all'
      - '../results/protect_ad/Contrast 0007/all'
      - '../results/protect_ad/Contrast 0010/all'
      - '../results/protect_ad/Contrast 0012/all'
      - '../results/protect_ad/Contrast 0014/all'
    modality_names:
      - 'Contrast 0002'
      - 'Contrast 0003'
      - 'Contrast 0004'
      - 'Contrast 0005'
      - 'Contrast 0006'
      - 'Contrast 0007'
      - 'Contrast 0010'
      - 'Contrast 0012'
      - 'Contrast 0014'
    group:
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
      - 'Task fMRI'
    skip: False